[package]
name = "fp_rust"
version = "0.1.0"
license = "MIT"
authors = ["JunYi JohnTeee Lee <johnteee@gmail.com>"]
include = ["src/**/*.rs", "Cargo.toml"]
description = "Implement fp features for Rust"

[dependencies]

[[test]]
name = "maybe"
path = "src/maybe.rs"
