[package]
name = "fp_rust"
version = "0.1.13"
license = "MIT"
authors = ["JunYi JohnTeee Lee <johnteee@gmail.com>"]
include = ["src/**/*.rs", "Cargo.toml"]
description = "Implement fp features for Rust"
documentation = "https://github.com/TeaEntityLab/fpRust/blob/master/README.md"
homepage = "https://github.com/TeaEntityLab/fpRust"
repository = "https://github.com/TeaEntityLab/fpRust"

[lib]
name = "fp_rust"
path = "src/lib.rs"

[features]
default = []

[dependencies]
